#-mode python-
Import('env')
env = env.Clone()

libsname=['kmq_common', 'profiler']
core_src = Glob('*.cc')
regmgr_src = Glob('regmgr/*.cc')
core_sources = [core_src, regmgr_src]

env.aLibrary(target = 'kmq_core', source = core_sources, LIBS = libsname)	  

coretest = env.aDirs('test')
cpps=[core_sources]
Return(['cpps'] )

